MyProject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^music/',include('music.urls')),
    url(r'^login/$', views.login,{'template_name':'music/login.html'}, name='login'),
    url(r'^logout/$',views.logout,name='logout')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns=[
    #/music
    url(r'^$',views.IndexView.as_view(),name='index'),

    # /music/register
    url(r'register$', views.UserFormView.as_view(), name='user'),

    #/music/5
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='detail'),

    # /music/album/add
    url(r'album/add/$', views.AlbumCreate.as_view(), name='albumAdd'),

    # /music/album/2/delete
    url(r'album/(?P<pk>[0-9])/delete/$', views.AlbumDelete.as_view(), name='album-delete'),

    #/music/album/2
    url(r'album/(?P<pk>[0-9]+)/$',views.AlbumUpdate.as_view(),name='album-update'),

    #/music/<album_id>/fav
    #url(r'^(?P<album_id>[0-9]+)/favorite/$',views.favorite,name='favorite')
]

music/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Album(models.Model):
    title = models.CharField(max_length=50)
    singer = models.CharField(max_length=40)
    year = models.CharField(max_length=4)
    Nos = models.IntegerField(null=True)
    #album_logo = models.CharField(max_length=300)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music:detail',kwargs={'pk':self.pk})

    def _str_(self):
        return self.title + ' === ' + self.singer


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=40)
    song_title = models.CharField(max_length=300)
    is_fav=models.BooleanField(default=False)

music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model =User
        fields =['username','email','password']

music/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Album,Song
from django.views import generic
from django.views.generic import View
from django.template import loader
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from django.contrib.auth import authenticate,login
from .forms import UserForm

# Create your views here.
from django.http import HttpResponse
from django.http import Http404

#def index(request):
 #   albums=Album.objects.all()
    #template = loader.get_template('music/index.html')
  #  context ={
   #     'albums':albums
    #}
    #return HttpResponse(template.render(context,request))
    #return render(request, 'music/index.html', context)

#def detail(request,album_id):
    #return HttpResponse("<h1>the album "+album_id+"</h1>")

    #try:
     #   album=Album.objects.get(pk=album_id)
    #except Album.DoesNotExist:
     #   raise Http404("Album Does not Exist")


    #http shortcut
 #   album = get_object_or_404(Album,pk=album_id)

  #  context = {
   #     'album': album
    #}
    #return render(request,'music/details.html',context)

#def favorite(request,album_id):
 #   album = get_object_or_404(Album, pk=album_id)
  #  try:
   #     selected_song=album.song_set.get(pk=request.POST['song'])
    #except (KeyError,Song.DoesNotExist):
     #   return render(request,'music/details.html',{'album':album , 'error_msg':'your song does not exits' })
    #else:
     #   selected_song.is_fav=True;
      #  selected_song.save()
       # return render(request,'music/details.html',{'album':album })


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'albums'

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DeleteView):
    model = Album
    template_name = 'music/details.html'

    def get_queryset(self):
        return Album.objects.all()


class AlbumCreate(CreateView):
    model = Album
    fields = ['title','singer','year','album_logo']
    template_name = 'music/album_form.html'


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['title','singer','year','album_logo']
    template_name = 'music/album_form.html'


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')


class UserFormView(View):
    form_class=UserForm
    template_name='music/registration_form.html'

    def get(self,request):
        form=self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form =self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            #Cleaning Path Making it Normalized
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            #return back if incorrect Credentials

            user=authenticate(username=username,password=password)

            if user is not None:
                if user.is_active:
                    login(request,user)
                    return redirect('music:index')

        return render(request, self.template_name, {'form': form})

music/templates/music/album_form.html
{% extends 'music/base.html'%}
{% block title%}Album Details{% endblock%}
{% block content%}

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'music/form-template.html'%}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Add Album</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock%}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title%}Listen{% endblock%}</title>
    <meta charset="UTF-8">
    <title>Title</title>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Tangerine:bold,bolditalic|Inconsolata:italic|Droid+Sans">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<nav class="navbar navbar-inverse" style="border-radius:0;">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">Listen</a>
        </div>
        <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li> <a href="#"><span class="glyphicon glyphicon-cd"></span> &nbsp Albums</a></li>
      <li> <a href="#"><span class="glyphicon glyphicon-music"></span>&nbsp Songs</a></li>
      <li><a href="#"><i class="fas fa-microphone"></i>&nbsp Artists</a></li>
    </ul>

        <form class="navbar-form navbar-left" role="search" action="#">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search" name="searchq">
        <div class="input-group-btn">
          <button class="btn btn-default" type="submit">
            <i class="glyphicon glyphicon-search"></i>
          </button>
        </div>
      </div>
    </form>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'music:albumAdd'%}"><span class="glyphicon glyphicon-plus"></span> Add Album</a></li>
      <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
            </div>
    </div>
</nav>
{% block content%}
{% endblock %}
</body>
</html>

music/templates/music/details.html
{% extends 'music/base.html'%}
{% block title%}Album Details{% endblock%}
{% block content%}
<div class="container">
    <h1>Details of the album</h1>
    <div class="jumbotron" id="details" style="background-image:url('{{album.album_logo}}');">
    <h1 class="display-3">{{album.title}} {{album.year}}</h1>
    <p class="lead">{{album.singer}}</p>
    <hr class="my-4">
    {% if error_message %}
        <p>{{error_message}}</p>
    {% endif%}
    <form action="" method="post">
        {% csrf_token %}

    <ul>
        {% for song in album.song_set.all %}
            <li><input type="radio" id="song{{forloop.counter}}" name="song" value="{{song.id}}"/> {{song.song_title}} - {{song.file_type}}
                {% if song.is_fav %}
                        <i class="fa fa-heart"></i>
                {% endif %}
            </li>
        {% endfor %}
    </ul>

        <button class="btn btn-primary btn-lg" type="submit" >Add to <i class="fa fa-heart" style="color:red"></i></button>
        </form>
</div>
</div>
{% endblock%}

music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{field.errors}}</span>
        </div>
        <label class="control-label col-sm-2">{{field.label_tag}}</label>
        <div class="col-sm-10">{{field}}</div>
    </div>
{%endfor%}

music/templates/music/index.html
{% extends 'music/base.html'%}
{% block content%}
{% if albums%}
    <ul>
        {% for album in albums%}
        <div class="card" style="width: 20rem;">
            <img class="card-img-top" src="{{album.album_logo.url}}" alt="Card image cap" style="width:200px;height:200px">
            <div class="card-body">
                <h4 class="card-title">{{album.title}} - {{album.year}}</h4>
                <p class="card-text">{{album.singer}}</p>
                <a href="{% url 'music:detail' album.id %}" class="btn btn-primary">View Album</a>
                <form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <input type="hidden" name="album_id" value="{{ album.id }}"/>
                    <button type="submit" class="btn btn-danger btn-small">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>
                </form>
            </div>
        </div>
        {% endfor %}
    </ul>
{% else %}
    <h1>NO Albums</h1>
{% endif %}
{% endblock%}

music/templates/music/login.html
{% extends 'music/base.html'%}
{% block title%}Login {% endblock%}
{% block content%}
<form method="post">
    {%csrf_token%}
    {{form.as_p}}
    <button type="submit">Login</button>
</form>
{% endblock%}

music/templates/music/registration_form.html
{% extends 'music/base.html'%}
{% block title%}Album Details{% endblock%}
{% block content%}

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>User Registation</h3>
                        {% if error_message %}
                            <p><strong>{{error_message}}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'music/form-template.html'%}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Add Album</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock%}